---
# Ref: https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser
blank_issues_enabled: false # default is true
contact_links:
  - name: Help and Support
    url: https://matrix.to/#/#aap_config_as_code:ansible.com
    about: Matrix room for questions. (or go to the forums)
  - name: Feature requests
<<<<<<< HEAD
    url: https://github.com/redhat-cop/controller_configuration/discussions/categories/ideas
    about: Suggest an idea for this project
  - name: Discussions
    url: https://github.com/redhat-cop/controller_configuration/discussions
    about: Any kind of questions should go on the forum.
  - name: Matrix room
    url: https://matrix.to/#/#aap_config_as_code:ansible.com
    about: Matrix room for questions and discussion.
=======
    url: https://forum.ansible.com/tag/infra-config-as-code
    about: Any kind of questions or ideas should go on the forum.
>>>>>>> 05b830566dcc61b49195ee27848426b7a0a12574
  - name: Ansible Code of Conduct
    url: https://docs.ansible.com/ansible/latest/community/code_of_conduct.html
    about: Be nice to other members of the community. Behave.
