---
# tasks file for controller_credential_types
- name: Get the organization ID
  ansible.builtin.set_fact:
    __controller_organization_id: "{{ lookup(controller_api_plugin, 'organizations', query_params={'name': orgs},
      host=controller_hostname, oauth_token=oauthtoken, verify_ssl=false) }}"

- name: "OBJECT DIFF: Get the API list of all Projects {{ orgs }} Organization"
  ansible.builtin.set_fact:
    __controller_api_credential_types: "{{ query(controller_api_plugin, 'credential_types',
                                                query_params={'managed': false},
                                                host=controller_hostname, oauth_token=controller_oauthtoken, verify_ssl=controller_validate_certs,
                                                return_all=true, max_objects=query_controller_api_max_objects)
                                        }}"
  when: is_aap

- name: "OBJECT DIFF: Get the API list of all Credential Types"
  ansible.builtin.set_fact:
    __controller_api_credential_types: "{{ query(controller_api_plugin, 'credential_types',
                                                query_params={'managed_by_tower': false},
                                                host=controller_hostname, oauth_token=controller_oauthtoken, verify_ssl=controller_validate_certs,
                                                return_all=true, max_objects=query_controller_api_max_objects)
                                        }}"
  when: not is_aap

- name: "OBJECT DIFF: Find the difference of Project between what is on the Controller versus CasC on SCM"
  ansible.builtin.set_fact:
    __credential_types_difference: "{{ query(controller_role_plugin,
                                             api_list=__controller_api_credential_types, compare_list=controller_credential_types,
                                             with_present=include_present_state, set_absent=true) | flatten
                                    }}"

- name: "OBJECT DIFF: Set credential's list to be configured"
  ansible.builtin.set_fact:
    controller_credential_types: "{{ __credential_types_difference }}"
...
