---
- name: "Gets current Organizations configured"
  ansible.builtin.set_fact:
    __controller_api_organizations: "{{ query(controller_api_plugin, 'organizations',
      host=controller_hostname, oauth_token=oauthtoken, verify_ssl=controller_validate_certs) }}"

- name: "Role differences (block)"
  when:
    - __controller_api_current_user_check_is_admin.is_superuser
  block:
    - name: "Gets current Organizations configured"
      ansible.builtin.set_fact:
        __controller_api_organizations: "{{ query(controller_api_plugin, 'organizations',
                                                  host=controller_hostname, oauth_token=controller_oauthtoken, verify_ssl=controller_validate_certs,
                                                  return_all=true, max_objects=query_controller_api_max_objects)
                                         }}"

- name: "Sets Organization differences"
  ansible.builtin.set_fact:
    controller_organizations: "{{ __organizations_difference }}"
...
