---
# https://github.com/marketplace/actions/issues-helper
<<<<<<< HEAD
name: Check inactive
=======
name: Check and close inactive
>>>>>>> 05b830566dcc61b49195ee27848426b7a0a12574

on:
  schedule:
    - cron: "0 6 * * *"

jobs:
  close-inactive-issues:
    runs-on: ubuntu-latest
    steps:
      - name: close-issues
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'close-issues'
          token: ${{ secrets.GITHUB_TOKEN }}
<<<<<<< HEAD
          labels: 'need info, inactive'
=======
          labels: 'inactive'
>>>>>>> 05b830566dcc61b49195ee27848426b7a0a12574
          inactive-day: 7
...
